name: Yarn Install

on:
  pull_request:
    branches: [ "main" ]

jobs:
  InstallPackages:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max_old_space_size=14000
    steps:
      - uses: actions/checkout@v4.1.7
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: yarn.lock

      - name: Install Packages 🔧
        run: yarn --frozen-lockfile
